movieproject/movielistapp/urls.py
from django.urls import path
from . import views
app_name='movielistapp'
urlpatterns = [

    path('',views.home,name='home'),
    path('movie/<int:movie_id>/',views.detail,name='details'),
    path('addmovie/',views.addmovie,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movielistapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movielistapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    moviename=models.CharField(max_length=250)
    director=models.CharField(max_length=250)
    industry=models.CharField(max_length=250)
    genre=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')


    def __str__(self):
        return self.moviename

movieproject/movielistapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['desc','img']

movieproject/movielistapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def home(requset):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(requset,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})
def addmovie(request):
    if request.method =='POST':
        moviename=request.POST.get('moviename',)
        director= request.POST.get('director',)
        industry = request.POST.get('industry',)
        genre = request.POST.get('genre',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(moviename=moviename,director=director,industry=industry,genre=genre,desc=desc,year=year,img=img)
        movie.save()

    return render(request,"addmovie.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,"delete.html")

movieproject/templates/addmovie.html
{% extends 'test.html' %}
{% load static %}
{% block body %}

 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link rel="stylesheet" href="{% static 'form.css' %}">
   <div class="main-block">

      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="title">
          <i class="fas fa-pencil-alt"></i>
          <h2>Add Movie here</h2>
        </div>
        <div class="info">
         <input type="text" name="moviename" placeholder=" Movie name">
         <input type="text" name="director" placeholder=" Director name">

           <select name="industry">
            <option value="course-type" selected>Industry</option>
            <option value="hollywood">Hollywood</option>
            <option value="bollywood">Bollywood</option>
            <option value="chinese">chinese</option>
            <option value="mollywood">mollywood</option>
            <option value="kollywood">kollywood</option>
            <option value="jappanese">jappanese</option>
            <option value="korean">korean</option>
               <option value="historical">Historical</option>
          </select>

          <select name="genre">
            <option value="course-type" selected>Category</option>
            <option value="action">Action</option>
            <option value="drama">Drama</option>
            <option value="horror">Horror</option>
            <option value="fantasy">Fantasy</option>
            <option value="comedy">Comedy</option>
            <option value="sciencefiction">science fiction</option>
            <option value="thriller">Thriller</option>
               <option value="historical">Historical</option>
          </select>

        <input type="text" name="desc" placeholder="Movie Description">
        <input type="text" name="year" placeholder="Movie Year">
        <input type="file" name="img">


        </div>

        <button type="submit" >Add Movie</button>
      </form>
    </div>
    {% endblock %}

movieproject/templates/delete.html
<form method="POST">

    {% csrf_token %}
    Are you read to delete ?
    <input type="submit" value="delete">
</form>

movieproject/templates/details.html
{% extends 'test.html' %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="{% static 'form.css' %}">
<div class="main-cont">
    <h3>{{movie.moviename}}({{movie.year}})</h3>
<img src="{{movie.img.url}}" width="300" height="300">
    <p style="color:black; font-size:25px; font-family:nyala;">Director:{{movie.director}}</p>
    <p style="color:black; font-size:20px; font-family:nyala;">Category:{{movie.genre}}</p>
    <p style="font-family:nyala; font-size:20px;">{{movie.desc}}</p>

    <button class="btn btn-success " style="left:-160px; top:53px;"><a style="color:white;" href="{%url 'movielistapp:update' movie.id %}">Update</a></button>
    <button class="btn btn-danger"><a style="color:white;" href="{%url 'movielistapp:delete' movie.id %}">Delete</a></button>
</div>
{% endblock %}

movieproject/templates/index.html
{% extends 'test.html' %}
{% block body %}
<br><br><br>
<h3 style="color:white">Movie list</h3>
{% for i in movie_list %}
<div>

<ul style="color:white; font-size:20px;">
    <li><a href="{% url 'movielistapp:details' i.id %}" style="color:blaack">{{i.moviename}}({{i.year}})</a></li>
</ul>
</div>
{% endfor %}
{% endblock %}

movieproject/templates/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie mojo</title>
    <link rel="stylesheet" href="{% static 'test.css' %}">
    <script src="{% static 'test.js' %}"></script>
</head>
<body>
    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<!--<div class="navbar navbar-fixed-top container-fluid" id="navbar">-->
<!--  	 <div class="navbar-header">-->
<!--      <button type="button" class="navbar-toggle navbar-default" data-toggle="collapse" data-target="#myNavbar">-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>                        -->
<!--      </button>-->

<!--    </div>-->
    <div class="collapse navbar-center navbar-collapse" id="myNavbar"  >
        <h3 style="font-family: nyala;color: yellow; font-size:30px;">Movie Mojo</h3>
    	<ul class="nav navbar-nav" >
            <li><a href="{% url 'movielistapp:home' %}" style="color:white">Home</a></li>
    		  <li><a href="{% url 'movielistapp:addmovie' %}" style="color:white">Add Movie</a></li>


    	</ul>

    </div>

<div>
{% block body %}
{% endblock %}
</div>
</body>

</html>

movieproject/templates/update.html
{% extends 'test.html' %}
{% block body %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}